name: Deploy to the main

on:
  push:
    branches:
      - main

jobs:
  redeploy_frontend:
    runs-on: ubuntu-latest
    name: Redeploying frontend to the staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH and Deploy
        env:
          SSH_SECRET_KEY: ${{ secrets.SSH_SECRET_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          echo "$SSH_SECRET_KEY" > ~/ssh_key
          chmod 600 ~/ssh_key
          
          mkdir -p ~/.ssh
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
          ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@43.204.100.21 << 'EOF'
            cd mono_dev
            pnpm install
            pnpm run build
            pm2 restart all
          EOF
